apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seuneuseu-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: dev-front.seuneuseu.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: seuneuseu-frontend
            port:
              number: 80
