apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

images:
  - name: my-nextjs-image
    newName: 036333380579.dkr.ecr.ap-northeast-1.amazonaws.com/kwonjh0406/seuneuseu-frontend
    newTag: latest
