apiVersion: apps/v1
kind: Deployment
metadata:
  name: seuneuseu-frontend
  labels:
    app: seuneuseu-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: seuneuseu-frontend
  template:
    metadata:
      labels:
        app: seuneuseu-frontend
    spec:
      containers:
      - name: seuneuseu-frontend
        image: my-nextjs-image
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
